files:
  competitions:
    path: C:\Users\Leonid\PycharmProjects\scheduleApplication\src\tables\Malesice\251220 Plzeň competitions (3).xlsx
    sheet: Competitions
  competitors:
    path: C:\Users\Leonid\PycharmProjects\scheduleApplication\src\tables\Malesice\251220 Plzeň registered (4).xlsx
    sheet: Competitors
  jury:
    path: C:\Users\Leonid\PycharmProjects\scheduleApplication\src\tables\Malesice\251220 Plzeň judges_2.xlsx
    sheet: Judges
  schedule:
    path: C:\Users\Leonid\PycharmProjects\scheduleApplication\src\tables\Malesice\harmonogram_7_čtvrtek_večer.xlsx
    sheet: harmonogram
columns:
  competitions:
    id: number
    title: composite
    discipline: discipline
    age: age
    rank: class
    competitor_count: people
    round_count: round_count
  competitors:
    assignment_prefix: "#"
    count: count
    p1_name_surname: p1_name_surname
    p2_name_surname: p2_name_surname
  jury:
    id: label
    name: jmeno
    surname: prijmeni
#    fullname: fullname
    assignment_prefix: "#"
  schedule:
    start_time: čas zahájení
#    end_time: čas ukončení
    duration: minut
    competition_id: id_competition
    round_type: kolo

